project:
  type: website
  output-dir: docs

website:
  title: "Nozimjon Ortikov"
  navbar:
    left:
      - about.qmd
      - text: "Blog"
        href: index.qmd
      

        
format:
  html:
    theme:
      - cosmo
      - custom.scss
    toc: true
    toc_depth: 3
    toc_float: true
    toc_smooth_scroll: true
    toc_highlight: true
    fig-align: center 

editor: visual

